/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Lexer.Lexer;

import java.io.StringReader;

public class Compiler {
    public static void main(String[] args) throws Exception {
        System.out.println("Hello from the compiler !");
        String input = "var x int = 2;\nvar y float = 3.14;\n var x int=12;\n var x  int =       12;";
        StringReader reader = new StringReader(input);
        Lexer lexer = new Lexer(reader);
        while (true) {
            var symbol = lexer.getNextSymbol();
            System.out.println(symbol);
            if (symbol.type == compiler.Lexer.TokenTypes.EOF) {
                break;
            }
        }

    }
}
